### ISSUE TITLE
请问为什么我在使用时会报错

### ISSUE THREAD

**Issue by jacksixth** [huankong233/node-napcat-ts#10]
![image](https://github.com/user-attachments/assets/d9e604f4-09bb-4280-bf8f-cb50af180df7)
这个是写的代码
![image](https://github.com/user-attachments/assets/9fc11c99-84a9-4da6-a608-8fab2a57e4e7)
这个是tsc后生成的

**Comment by huankong233** [comment]
> ![image](https://private-user-images.githubusercontent.com/42532036/354168920-d9e604f4-09bb-4280-bf8f-cb50af180df7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTI1NzYsIm5iZiI6MTcyMjUxMjI3NiwicGF0aCI6Ii80MjUzMjAzNi8zNTQxNjg5MjAtZDllNjA0ZjQtMDliYi00MjgwLWJmOGYtY2I1MGFmMTgwZGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDExMzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDhjMzJhYzNjZjhlMmU0YzU4N2NlZTdlNTQyNGU1NDA3OWRkMzA2YjhjN2YwMzFhM2RkMjAzZTQxZThkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ab8mxcK3eHobeA0qZCnrkRmGpVYEyjYfeDGhV8pq7Hs) 这个是写的代码 ![image](https://private-user-images.githubusercontent.com/42532036/354169108-9fc11c99-84a9-4da6-a608-8fab2a57e4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTI1NzYsIm5iZiI6MTcyMjUxMjI3NiwicGF0aCI6Ii80MjUzMjAzNi8zNTQxNjkxMDgtOWZjMTFjOTktODRhOS00ZGE2LWE2MDgtOGZhYjJhNTdlNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDExMzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYjlmNjcyNDg0NDcxNTAyNDc3YmJiOTBmNzMyZTYyYWJiZjI5NzdkOThjOTFkNGJjOWNmZTgxYWY3NjMzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UFPZ7O8hPZJIWHqkaiCofsckJOvhMhtp0E5KKq9b8I4) 这个是tsc后生成的

有两种解决方法

- 1.编译时编译成 `es` 模块
- 2.直接使用 `tsx` 执行,不编译成 `js`
- 3.使用 `bun` 执行项目（未测试兼容情况）
