### ISSUE TITLE
bug代码用不了

### ISSUE THREAD

**Issue by wordgao** [huankong233/node-napcat-ts#19]
测试某接口得到的结果是如下
`
// 初始化
const bot = new NCWebsocket({
  baseUrl: "ws://127.0.0.1:3001",
  accessToken: "",
})

// const bot = new NCWebsocket({
//   protocol: 'ws',
//   host: 'localhost',
//   port: 5001,
//   accessToken: '',
// },false)
// bot.connect()
bot.connect()
`
结果
`
node-napcat-ts.js?v=f84ed0ba:42 Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code. See 

https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

`

`
main.ts:32 [Vue Router warn]: uncaught error during route navigation:
`
`TypeError: Class extends value undefined is not a constructor or null
at node-napcat-ts.js?v=f84ed0ba:120:46
`

`
[Vue Router warn]: Unexpected error when starting the router: TypeError: Class extends value undefined is not a constructor or null

at node-napcat-ts.js?v=f84ed0ba:120:46
`

**Comment by huankong233** [comment]
> 测试某接口得到的结果是如下 ` // 初始化 const bot = new NCWebsocket({ baseUrl: "ws://127.0.0.1:3001", accessToken: "", })
> 
> // const bot = new NCWebsocket({ // protocol: 'ws', // host: 'localhost', // port: 5001, // accessToken: '', // },false) // bot.connect() bot.connect() `结果` node-napcat-ts.js?v=f84ed0ba:42 Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code. See
> 
> https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
> 
> `
> 
> `main.ts:32 [Vue Router warn]: uncaught error during route navigation:` `TypeError: Class extends value undefined is not a constructor or null at node-napcat-ts.js?v=f84ed0ba:120:46 `
> 
> ` [Vue Router warn]: Unexpected error when starting the router: TypeError: Class extends value undefined is not a constructor or null
> 
> at node-napcat-ts.js?v=f84ed0ba:120:46 `

看样子问题是未加载 `events` 包,请尝试 `0.1.10` 查看是否解决

**Comment by wordgao** [comment]
## 问题依旧
`
Uncaught (in promise) Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new module.exports (node-napcat-ts.js?v=f26bc5cb:29:13)
    at NCWebsocketApi.connect (node-napcat-ts.js?v=f26bc5cb:657:33)
    at setup (napbot.vue:23:5)
    at callWithErrorHandling (chunk-544CHW4L.js?v=f26bc5cb:1678:19)
    at setupStatefulComponent (chunk-544CHW4L.js?v=f26bc5cb:9179:25)
    at setupComponent (chunk-544CHW4L.js?v=f26bc5cb:9140:36)
    at mountComponent (chunk-544CHW4L.js?v=f26bc5cb:6356:7)
    at processComponent (chunk-544CHW4L.js?v=f26bc5cb:6322:9)
    at patch (chunk-544CHW4L.js?v=f26bc5cb:5838:11)
    at mountChildren (chunk-544CHW4L.js?v=f26bc5cb:6070:7)
`

**Comment by huankong233** [comment]
> ## 问题依旧
> `Uncaught (in promise) Error: ws does not work in the browser. Browser clients must use the native WebSocket object at new module.exports (node-napcat-ts.js?v=f26bc5cb:29:13) at NCWebsocketApi.connect (node-napcat-ts.js?v=f26bc5cb:657:33) at setup (napbot.vue:23:5) at callWithErrorHandling (chunk-544CHW4L.js?v=f26bc5cb:1678:19) at setupStatefulComponent (chunk-544CHW4L.js?v=f26bc5cb:9179:25) at setupComponent (chunk-544CHW4L.js?v=f26bc5cb:9140:36) at mountComponent (chunk-544CHW4L.js?v=f26bc5cb:6356:7) at processComponent (chunk-544CHW4L.js?v=f26bc5cb:6322:9) at patch (chunk-544CHW4L.js?v=f26bc5cb:5838:11) at mountChildren (chunk-544CHW4L.js?v=f26bc5cb:6070:7)`

这个好像要单独打包 `websocket` 成浏览器的对象

不太会用怎么办🤔，貌似就要加上 `vite` 什么的打包工具了

**Comment by wordgao** [comment]
## dispatcher.ts
`
class Log {
    private static console = true;
    log(title: string, text: string) {
        if (!Log.console) return;
        if (import.meta.env.MODE === 'production') return;
        const color = '#ff4d4f';
        console.log(
            `%c ${title} %c ${text} %c`,
            `background:${color};border:1px solid ${color}; padding: 1px; border-radius: 2px 0 0 2px; color: #fff;`,
            `border:1px solid ${color}; padding: 1px; border-radius: 0 2px 2px 0; color: ${color};`,
            'background:transparent'
        );
    }
    closeConsole() {
        Log.console = false;
    }
}
export class EventDispatcher extends Log {
    private listeners: { [type: string]: Function[] } = {};

    protected addEventListener(type: string, listener: Function) {
        if (!this.listeners[type]) {
            this.listeners[type] = [];
        }
        if (this.listeners[type].indexOf(listener) === -1) {
            this.listeners[type].push(listener);
        }
    }

    protected removeEventListener(type: string) {
        this.listeners[type] = [];
    }

    protected dispatchEvent(type: string, data: any) {
        const listenerArray = this.listeners[type] || [];
        if (listenerArray.length === 0) return;
        listenerArray.forEach(listener => {
            listener.call(this, data);
        });
    }
}
`
## WebSocketClient.ts
`

import { EventDispatcher } from './dispatcher.ts';

// https://mp.weixin.qq.com/s/DmmUa-0OPFcTpf5jW232rw

export class WebSocketClient extends EventDispatcher {
    // #socket链接
    private url = '';
    // #socket实例
    private socket: WebSocket | null = null;
    // #重连次数
    private reconnectAttempts = 0;
    // #最大重连数
    private maxReconnectAttempts = 5;
    // #重连间隔
    private reconnectInterval = 10000; // 10 seconds
    // #发送心跳数据间隔
    private heartbeatInterval = 1000 * 30;
    // #计时器id
    private heartbeatTimer?: NodeJS.Timeout;
    // #彻底终止ws
    private stopWs = false;
    // *构造函数
    constructor(url: string) {
        super();
        this.url = url;
    }
    // >生命周期钩子
    onopen(callBack: Function) {
        this.addEventListener('open', callBack);
        
    }
    onmessage(callBack: Function) {        
        this.addEventListener('message', callBack);        
    }
    // onnotice(callBack: Function) {        
    //     this.addEventListener('notice', callBack);        
    // }

    // onmeta_event(callBack: Function) {        
    //     this.addEventListener('meta_event', callBack);        
    // }
    // ongroup_ban(callBack: Function) {        
    //     this.addEventListener('group_ban', callBack);        
    // }
    // ongroup_decrease(callBack: Function) {        
    //     this.addEventListener('group_decrease', callBack);        
    // }

    // ongroup_increase(callBack: Function) {        
    //     this.addEventListener('group_increase', callBack);        
    // }
    // ongroup(callBack: Function) {        
    //     this.addEventListener('group', callBack);        
    // }
    // onprivate(callBack: Function) {        
    //     this.addEventListener('private', callBack);        
    // }



    onclose(callBack: Function) {
        this.addEventListener('close', callBack);
    }
    onerror(callBack: Function) {
        this.addEventListener('error', callBack);
    }
    // >消息发送
    public send(message: string): void {
        if (this.socket && this.socket.readyState === WebSocket.OPEN) {
            this.socket.send(message);
        } else {
            console.error('[WebSocket] 未连接');
        }
    }

    // !初始化连接
    public connect(): void {
        if (this.reconnectAttempts === 0) {
            this.log('WebSocket', `初始化连接中...          ${this.url}`);
        }
        if (this.socket && this.socket.readyState === WebSocket.OPEN) {
            return;
        }
        this.socket = new WebSocket(this.url);

        // !websocket连接成功
        this.socket.onopen = event => {
            this.stopWs = false;
            // 重置重连尝试成功连接
            this.reconnectAttempts = 0;
            // 在连接成功时停止当前的心跳检测并重新启动
            this.startHeartbeat();
            this.log('WebSocket', `连接成功,等待服务端数据推送[onopen]...     ${this.url}`);
            this.dispatchEvent('open', event);
            
        };

        this.socket.onmessage = event => {
            this.dispatchEvent('message', event);
            this.startHeartbeat();
        };

        this.socket.onclose = event => {
            if (this.reconnectAttempts === 0) {
                this.log('WebSocket', `连接断开[onclose]...    ${this.url}`);
            }
            if (!this.stopWs) {
                this.handleReconnect();
            }
            this.dispatchEvent('close', event);
        };

        this.socket.onerror = event => {
            if (this.reconnectAttempts === 0) {
                this.log('WebSocket', `连接异常[onerror]...    ${this.url}`);
            }
            this.closeHeartbeat();
            this.dispatchEvent('error', event);
        };
    }

    // > 断网重连逻辑
    private handleReconnect(): void {
        if (this.reconnectAttempts < this.maxReconnectAttempts) {
            this.reconnectAttempts++;
            this.log('WebSocket', `尝试重连... (${this.reconnectAttempts}/${this.maxReconnectAttempts})       ${this.url}`);
            setTimeout(() => {
                this.connect();
            }, this.reconnectInterval);
        } else {
            this.closeHeartbeat();
            this.log('WebSocket', `最大重连失败，终止重连: ${this.url}`);
        }
    }

    // >关闭连接
    public close(): void {
        if (this.socket) {
            this.stopWs = true;
            this.socket.close();
            this.socket = null;
            this.removeEventListener('open');
            this.removeEventListener('message');
            this.removeEventListener('close');
            this.removeEventListener('error');
        }
        this.closeHeartbeat();
    }

    // >开始心跳检测 -> 定时发送心跳消息
    private startHeartbeat(): void {
        if (this.stopWs) return;
        if (this.heartbeatTimer) {
            this.closeHeartbeat();
        }
        this.heartbeatTimer = setInterval(() => {
            if (this.socket) {
                this.socket.send(JSON.stringify({ type: 'heartBeat', data: {} }));
                this.log('WebSocket', '送心跳数据...');
            } else {
                console.error('[WebSocket] 未连接');
            }
        }, this.heartbeatInterval);
    }

    // >关闭心跳
    private closeHeartbeat(): void {
        clearInterval(this.heartbeatTimer);
        this.heartbeatTimer = undefined;
    }
}
`
抄作业，我也是抄的。

**Comment by huankong233** [comment]
> ## dispatcher.ts
> `class Log { private static console = true; log(title: string, text: string) { if (!Log.console) return; if (import.meta.env.MODE === 'production') return; const color = '#ff4d4f'; console.log(`%c ${title} %c ${text} %c`, `background:${color};border:1px solid ${color}; padding: 1px; border-radius: 2px 0 0 2px; color: #fff;`, `border:1px solid ${color}; padding: 1px; border-radius: 0 2px 2px 0; color: ${color};`, 'background:transparent' ); } closeConsole() { Log.console = false; } } export class EventDispatcher extends Log { private listeners: { [type: string]: Function[] } = {};
> 
> ```
> protected addEventListener(type: string, listener: Function) {
>     if (!this.listeners[type]) {
>         this.listeners[type] = [];
>     }
>     if (this.listeners[type].indexOf(listener) === -1) {
>         this.listeners[type].push(listener);
>     }
> }
> 
> protected removeEventListener(type: string) {
>     this.listeners[type] = [];
> }
> 
> protected dispatchEvent(type: string, data: any) {
>     const listenerArray = this.listeners[type] || [];
>     if (listenerArray.length === 0) return;
>     listenerArray.forEach(listener => {
>         listener.call(this, data);
>     });
> }
> ```
> 
> } `
> 
> ## WebSocketClient.ts
> `
> 
> import { EventDispatcher } from './dispatcher.ts';
> 
> ### 抄袭地址
> // https://mp.weixin.qq.com/s/DmmUa-0OPFcTpf5jW232rw
> 
> export class WebSocketClient extends EventDispatcher { // #socket链接 private url = ''; // #socket实例 private socket: WebSocket | null = null; // #重连次数 private reconnectAttempts = 0; // #最大重连数 private maxReconnectAttempts = 5; // #重连间隔 private reconnectInterval = 10000; // 10 seconds // #发送心跳数据间隔 private heartbeatInterval = 1000 * 30; // #计时器id private heartbeatTimer?: NodeJS.Timeout; // #彻底终止ws private stopWs = false; // *构造函数 constructor(url: string) { super(); this.url = url; } // >生命周期钩子 onopen(callBack: Function) { this.addEventListener('open', callBack);
> 
> ```
> }
> onmessage(callBack: Function) {        
>     this.addEventListener('message', callBack);        
> }
> // onnotice(callBack: Function) {        
> //     this.addEventListener('notice', callBack);        
> // }
> 
> // onmeta_event(callBack: Function) {        
> //     this.addEventListener('meta_event', callBack);        
> // }
> // ongroup_ban(callBack: Function) {        
> //     this.addEventListener('group_ban', callBack);        
> // }
> // ongroup_decrease(callBack: Function) {        
> //     this.addEventListener('group_decrease', callBack);        
> // }
> 
> // ongroup_increase(callBack: Function) {        
> //     this.addEventListener('group_increase', callBack);        
> // }
> // ongroup(callBack: Function) {        
> //     this.addEventListener('group', callBack);        
> // }
> // onprivate(callBack: Function) {        
> //     this.addEventListener('private', callBack);        
> // }
> 
> 
> 
> onclose(callBack: Function) {
>     this.addEventListener('close', callBack);
> }
> onerror(callBack: Function) {
>     this.addEventListener('error', callBack);
> }
> // >消息发送
> public send(message: string): void {
>     if (this.socket && this.socket.readyState === WebSocket.OPEN) {
>         this.socket.send(message);
>     } else {
>         console.error('[WebSocket] 未连接');
>     }
> }
> 
> // !初始化连接
> public connect(): void {
>     if (this.reconnectAttempts === 0) {
>         this.log('WebSocket', `初始化连接中...          ${this.url}`);
>     }
>     if (this.socket && this.socket.readyState === WebSocket.OPEN) {
>         return;
>     }
>     this.socket = new WebSocket(this.url);
> 
>     // !websocket连接成功
>     this.socket.onopen = event => {
>         this.stopWs = false;
>         // 重置重连尝试成功连接
>         this.reconnectAttempts = 0;
>         // 在连接成功时停止当前的心跳检测并重新启动
>         this.startHeartbeat();
>         this.log('WebSocket', `连接成功,等待服务端数据推送[onopen]...     ${this.url}`);
>         this.dispatchEvent('open', event);
>         
>     };
> 
>     this.socket.onmessage = event => {
>         this.dispatchEvent('message', event);
>         this.startHeartbeat();
>     };
> 
>     this.socket.onclose = event => {
>         if (this.reconnectAttempts === 0) {
>             this.log('WebSocket', `连接断开[onclose]...    ${this.url}`);
>         }
>         if (!this.stopWs) {
>             this.handleReconnect();
>         }
>         this.dispatchEvent('close', event);
>     };
> 
>     this.socket.onerror = event => {
>         if (this.reconnectAttempts === 0) {
>             this.log('WebSocket', `连接异常[onerror]...    ${this.url}`);
>         }
>         this.closeHeartbeat();
>         this.dispatchEvent('error', event);
>     };
> }
> 
> // > 断网重连逻辑
> private handleReconnect(): void {
>     if (this.reconnectAttempts < this.maxReconnectAttempts) {
>         this.reconnectAttempts++;
>         this.log('WebSocket', `尝试重连... (${this.reconnectAttempts}/${this.maxReconnectAttempts})       ${this.url}`);
>         setTimeout(() => {
>             this.connect();
>         }, this.reconnectInterval);
>     } else {
>         this.closeHeartbeat();
>         this.log('WebSocket', `最大重连失败，终止重连: ${this.url}`);
>     }
> }
> 
> // >关闭连接
> public close(): void {
>     if (this.socket) {
>         this.stopWs = true;
>         this.socket.close();
>         this.socket = null;
>         this.removeEventListener('open');
>         this.removeEventListener('message');
>         this.removeEventListener('close');
>         this.removeEventListener('error');
>     }
>     this.closeHeartbeat();
> }
> 
> // >开始心跳检测 -> 定时发送心跳消息
> private startHeartbeat(): void {
>     if (this.stopWs) return;
>     if (this.heartbeatTimer) {
>         this.closeHeartbeat();
>     }
>     this.heartbeatTimer = setInterval(() => {
>         if (this.socket) {
>             this.socket.send(JSON.stringify({ type: 'heartBeat', data: {} }));
>             this.log('WebSocket', '送心跳数据...');
>         } else {
>             console.error('[WebSocket] 未连接');
>         }
>     }, this.heartbeatInterval);
> }
> 
> // >关闭心跳
> private closeHeartbeat(): void {
>     clearInterval(this.heartbeatTimer);
>     this.heartbeatTimer = undefined;
> }
> ```
> 
> } ` 抄作业，我也是抄的。

我刚刚看了下，可以用 window.WebSocket 来判断是否是浏览器环境，但是参数貌似不同，晚点我再看看

**Comment by wordgao** [comment]
源代码，我下载到本地编译，发现 
NCEventsBus.ts中的 包有问题
import { EventEmitter } from 'events'
顺便检查一下这个。

**Comment by huankong233** [comment]
> 源代码，我下载到本地编译，发现 NCEventsBus.ts中的 包有问题 import { EventEmitter } from 'events' 顺便检查一下这个。

这个有什么问题嘛，我这没问题啊🤔

**Comment by huankong233** [comment]
请尝试版本 `0.2.2` 问题是否解决

## 问题关联

[https://www.npmjs.com/package/ws](https://www.npmjs.com/package/ws)

## 问题

Note: This module does not work in the browser. The client in the docs is a reference to a backend with the role of a client in the WebSocket communication. Browser clients must use the native [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) object. To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like [isomorphic-ws](https://github.com/heineiuo/isomorphic-ws).

**Comment by wordgao** [comment]
可以正常链接到WS了，浏览器上面不在报错。还未测试下一步事件的监控和信息的回复。

**Comment by huankong233** [comment]
> 可以正常链接到WS了，浏览器上面不在报错。还未测试下一步事件的监控和信息的回复。

好的，如有问题请继续

**Comment by wordgao** [comment]
目前只是可以链接，接收到信息，目前好像还有一些信息获取不到，比如群来源信息，来自什么群，发送人信息 等字段丢失。

**Comment by huankong233** [comment]
> 目前只是可以链接，接收到信息，目前好像还有一些信息获取不到，比如群来源信息，来自什么群，发送人信息 等字段丢失。

这些收不到应该就不是我这里的问题了，或许可以给一个最小示例

**Comment by wordgao** [comment]
换个方式问吧，
我想获取信息来源，比如群名称，用户名称，
通过context.什么方式来获取。

**Comment by huankong233** [comment]
> 换个方式问吧， 我想获取信息来源，比如群名称，用户名称， 通过context.什么方式来获取。

`node` 环境一切正常

**Comment by huankong233** [comment]
> 可以检查一下structs.js文件中的结构是否完整。

和这个文件一点关系都没有的，这个文件只符合构建 `消息段`

**Comment by wordgao** [comment]
我认为接下来的工作，应该就是这个文件的对接匹配工作了。
我看不到获取群名称的字段。
目前环境都是正常的。
包括context下面的send字段.

**Comment by huankong233** [comment]
> 我认为接下来的工作，应该就是这个文件的对接匹配工作了。 我看不到获取群名称的字段。 目前环境都是正常的。 包括context下面的send字段.

你输出 `context` 看看呢，给个截图

**Comment by huankong233** [comment]
> > 我认为接下来的工作，应该就是这个文件的对接匹配工作了。 我看不到获取群名称的字段。 目前环境都是正常的。 包括context下面的send字段.
> 
> 你输出 `context` 看看呢，给个截图

![image](https://github.com/user-attachments/assets/e7904e35-4106-4cb9-85e4-088a9e53f1e8)

**Comment by huankong233** [comment]
> 我认为接下来的工作，应该就是这个文件的对接匹配工作了。 我看不到获取群名称的字段。 目前环境都是正常的。 包括context下面的send字段.

请查看文档 [https://blog.huankong.top/docs/node-napcat-ts/%E4%BD%BF%E7%94%A8/%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6/](https://blog.huankong.top/docs/node-napcat-ts/%E4%BD%BF%E7%94%A8/%E7%9B%91%E5%90%AC%E4%BA%8B%E4%BB%B6/)

`send` 方法是实例化后的类而已

需要使用 `on` 方法绑定事件触发

在触发后的 `context` 中可以收到对应的信息

我们一般称 `const napcat = new NCWebsocket(config)`

**Comment by huankong233** [comment]
这里是我自己使用的初始化函数, 来自 [`kkbot-ts`](https://github.com/huankong233/kkbot-ts/tree/dev/src/plugins/builtIn/bot/index.ts)

~~~ typescript
async init() {
    return new Promise((resolve, reject) => {
      const bot = new NCWebsocket(config.connect)

      if (debug) {
        bot.on('api.preSend', (context) => {
          this.logger.DEBUG('发送API请求')
          this.logger.DIR(context)
        })
        bot.on('api.response.success', (context) => {
          this.logger.DEBUG('收到API成功响应')
          this.logger.DIR(context)
        })
        bot.on('api.response.failure', (context) => {
          this.logger.DEBUG('收到API失败响应')
          this.logger.DIR(context)
        })
      }

      bot.on('socket.connecting', (context) => {
        this.logger.INFO(
          `连接中#${context.reconnection.nowAttempts}/${context.reconnection.attempts}`
        )
      })

      bot.on('socket.error', (context) => {
        this.logger.ERROR(
          `连接失败#${context.reconnection.nowAttempts}/${context.reconnection.attempts}`
        )
        this.logger.ERROR(context)

        if (context.reconnection.nowAttempts >= context.reconnection.attempts) {
          reject(`重试次数超过设置的${context.reconnection.attempts}次!`)
          throw new Error(`重试次数超过设置的${context.reconnection.attempts}次!`)
        }
      })

      bot.on('socket.open', async (context) => {
        this.logger.SUCCESS(
          `连接成功#${context.reconnection.nowAttempts}/${context.reconnection.attempts}`
        )
        await this.connectSuccess(bot)
        resolve(true)
      })

      bot.connect()
    })
  }
~~~

**Comment by wordgao** [comment]
缺少raw内容，这里包含peerName群名称和一些相关信息，
另外这里可能存在兼容性，以及接口标准one11还是12以及实际应用的匹配。

![QQ20240826-094523](https://github.com/user-attachments/assets/6e5655c0-4787-4d90-8fc7-a2010673f885)

**Comment by huankong233** [comment]
> 缺少raw内容，这里包含peerName群名称和一些相关信息， 另外这里可能存在兼容性，以及接口标准one11还是12以及实际应用的匹配。
> 
> ![QQ20240826-094523](https://private-user-images.githubusercontent.com/10544395/361278877-6e5655c0-4787-4d90-8fc7-a2010673f885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MzcxNzMsIm5iZiI6MTcyNDYzNjg3MywicGF0aCI6Ii8xMDU0NDM5NS8zNjEyNzg4NzctNmU1NjU1YzAtNDc4Ny00ZDkwLThmYzctYTIwMTA2NzNmODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAxNDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNTUyODVlOGVhODRiOTdhN2RlNGVjNmFhMDNkODI1OTUwYWMxODhkNjVlYmNmZGQ4ZTNhYTlhZGEwYTRlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-qiD2ASJL0k399dPZ1RMvvxohGWUbsrI7loztrQUhp8)

所有类型完全按照 `napcat` 实现

具体接口标准按照 `napcat` 为准

`napcat` 按照 `onebot11` 实现

缺少 `raw` 字段是因为在 `napcat` 中 需要打开 `debug` 中的开关

**Comment by wordgao** [comment]
![QQ222222](https://github.com/user-attachments/assets/af7c8987-983a-4a29-b268-28b7d164eca3)

**Comment by huankong233** [comment]
> ![QQ222222](https://private-user-images.githubusercontent.com/10544395/361279440-af7c8987-983a-4a29-b268-28b7d164eca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MzczNDUsIm5iZiI6MTcyNDYzNzA0NSwicGF0aCI6Ii8xMDU0NDM5NS8zNjEyNzk0NDAtYWY3Yzg5ODctOTgzYS00YTI5LWIyNjgtMjhiN2QxNjRlY2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAxNTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZmRmOWExNjAzNjJkMzYzOGNkZDNlYWVkODc5Mjg3ZWVlNTRjM2QyN2E4YmUwN2Q1OGU2NjQyZTBiYTI4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._0SgHpUcYwntPhtutBYSc7X-ZuEvKzbhkMeI-_WDRiQ)

[https://napneko.github.io/zh-CN/guide/config/basic](https://napneko.github.io/zh-CN/guide/config/basic)

**Comment by wordgao** [comment]
调试模式打开后可以看到群名称,但是struct缺少获取的结构字段。

**Comment by huankong233** [comment]
> 调试模式打开后可以看到群名称,但是struct缺少获取的结构字段。

直接 `context.message` 不就可以拿到了吗

**Comment by wordgao** [comment]
拿不到，message，只不过是信息列表，这里只包含信息以及at等相关信息，
拿不到群名称以及发件人信息。

![截图 2024-08-26 09-56-36](https://github.com/user-attachments/assets/f23cb81c-6860-4786-86dc-a6c363f124d3)

**Comment by huankong233** [comment]
> 拿不到，message，只不过是信息列表，这里只包含信息以及at等相关信息， 拿不到群名称以及发件人信息。
> 
> ![截图 2024-08-26 09-56-36](https://private-user-images.githubusercontent.com/10544395/361280385-f23cb81c-6860-4786-86dc-a6c363f124d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Mzc3OTUsIm5iZiI6MTcyNDYzNzQ5NSwicGF0aCI6Ii8xMDU0NDM5NS8zNjEyODAzODUtZjIzY2I4MWMtNjg2MC00Nzg2LTg2ZGMtYTZjMzYzZjEyNGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAxNTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYzRlNDZiZmQwYTE4ZTY4ZTQ3MmNhMzY4ZjBlNzk0MTE1YTY5MmU4MmYyZjYzZWZiYTllN2Y0NTc2YmI4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G9SXulysY8NpM0KEKoQel7VVTd2S-uX5Q6EvKIHm8NA)

对啊，哥们，你看看 `context` 上呢
