### ISSUE TITLE
代码开发可以，编译不了

### ISSUE THREAD

**Issue by wordgao** [huankong233/node-napcat-ts#34]
![截图 2024-09-02 13-23-25](https://github.com/user-attachments/assets/574e625a-b3ac-46eb-885c-43d7c4c5c97b)

**Comment by huankong233** [comment]
更新 `0.2.9` 版本

**Comment by wordgao** [comment]
测试编译通过！已OK。

**Comment by huankong233** [comment]
惩罚你给我点 star
