### ISSUE TITLE
关于 socket 事件的一点点想法

### ISSUE THREAD

**Issue by ry0513** [huankong233/node-napcat-ts#35]
嗨，大佬，
目前 socket 如下，
![image](https://github.com/user-attachments/assets/e7b3cd04-cc9b-4761-a2bb-d656789ae2db)
但是 open 事件实际为 WebSocket 连接建立成功，尚未通过服务器验证，
该项目是 针对 napcat 开发的 SDK ，能否添加一个 `success` 事件呢，用来表示成功连接到 napcat 服务，
类似于
```js
  // ==================WebSocket操作=============================
connect() {
    // 省略其他
    // ...
    socket.onopen = () => {
        // console.log("WebSocket 连接建立成功，等待服务器验证...");
        this.#eventBus.emit('socket.open', { reconnection: this.#reconnection })
        this.#reconnection.nowAttempts = 1
    }

    socket.onmessage = (event) => {
        const data = JSON.parse(event.data);
        if ('服务器验证成功') {
            this.#eventBus.emit('socket.success', xxx)
        } else if ('非服务器验证信息') {
            //进入下一个环节
            this.#message(event.data)
        }
    };
    // 省略其他
    // ...
}
```

**Comment by ry0513** [comment]
目前如果 accessToken 填写错误的话，但是填写的人不知道 accessToken 是错误的情况下，会先执行  open 事件然后执行 close 事件，然后自动开始重试，并重复执行上述事件，不会抛出认证失败的消息，如果有`success`事件，或者`认证失败`的事件，可能这样可以更明确一些，
```js
    const bot = new NCWebsocket({
      baseUrl: "ws://xxxxx",
      accessToken: "",
    });
    bot.on("socket.connecting", () => {
      console.log(`正在连接Bot服务`);
    });
    bot.on("socket.open", () => {
      console.log("WebSocket 连接建立成功，等待服务器验证...");
    });
    bot.on("socket.success", () => {
      console.log(`连接Bot服务成功`);
    });
    bot.on("socket.error", () => {
      console.log(`连接Bot服务失败`);
    });
    bot.on("socket.close", () => {
      console.log(`连接Bot服务断开`);
    });

    bot.connect();
```

**Comment by huankong233** [comment]
> 目前如果 accessToken 填写错误的话，但是填写的人不知道 accessToken 是错误的情况下，会先执行 open 事件然后执行 close 事件，然后自动开始重试，并重复执行上述事件，不会抛出认证失败的消息，如果有`success`事件，或者`认证失败`的事件，可能这样可以更明确一些，
> 
> ```js
>     const bot = new NCWebsocket({
>       baseUrl: "ws://xxxxx",
>       accessToken: "",
>     });
>     bot.on("socket.connecting", () => {
>       console.log(`正在连接Bot服务`);
>     });
>     bot.on("socket.open", () => {
>       console.log("WebSocket 连接建立成功，等待服务器验证...");
>     });
>     bot.on("socket.success", () => {
>       console.log(`连接Bot服务成功`);
>     });
>     bot.on("socket.error", () => {
>       console.log(`连接Bot服务失败`);
>     });
>     bot.on("socket.close", () => {
>       console.log(`连接Bot服务断开`);
>     });
> 
>     bot.connect();
> ```

这个最好要和 `napcat` 那边对接申请一下，毕竟 `SDK` 这边要实现这个不太方便，因为 `SDK` 也不知道是 `accesssToken` 有误还是超时了

**Comment by ry0513** [comment]
好像是有一些区分的，
![image](https://github.com/user-attachments/assets/4d9f0d80-fae7-4732-8eaa-e146b1f4b894)
分别点击按钮后，控制台如下
![image](https://github.com/user-attachments/assets/47fab1a8-00aa-4e9c-be27-2e83bd74333e)

**Comment by huankong233** [comment]
> 好像是有一些区分的， ![image](https://private-user-images.githubusercontent.com/44745967/365109945-4d9f0d80-fae7-4732-8eaa-e146b1f4b894.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njg1OTcsIm5iZiI6MTcyNTY2ODI5NywicGF0aCI6Ii80NDc0NTk2Ny8zNjUxMDk5NDUtNGQ5ZjBkODAtZmFlNy00NzMyLThlYWEtZTE0NmIxZjRiODk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTM1Y2NjODJkZjVhYzhiMzAzZWE5NjcyMmZkODk5NmQ5NmJmNmVkNDliNzQ4Yzk1YmQxODA4NjI2MTYzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPh0WHR8YwIe1aWKnZAx4wMKLRa1QyFxQciJ1uGOcbY) 分别点击按钮后，控制台如下 ![image](https://private-user-images.githubusercontent.com/44745967/365110992-47fab1a8-00aa-4e9c-be27-2e83bd74333e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njg1OTcsIm5iZiI6MTcyNTY2ODI5NywicGF0aCI6Ii80NDc0NTk2Ny8zNjUxMTA5OTItNDdmYWIxYTgtMDBhYS00ZTljLWJlMjctMmU4M2JkNzQzMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NjIyYWNhZjBkOGYyZmNhMTIzMTlhNGJiM2EyMjZiOWY0YjBlOWM0YTQ1YTllNDA3ZTMxNTIyNzdjYTgzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIvfL1Sb-neWrB6KPb59Es3uBiiu2up_tP1FkrXXQbc)

可能现在有了，我等下看看

**Comment by huankong233** [comment]
> > 好像是有一些区分的， ![image](https://private-user-images.githubusercontent.com/44745967/365109945-4d9f0d80-fae7-4732-8eaa-e146b1f4b894.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njg1OTcsIm5iZiI6MTcyNTY2ODI5NywicGF0aCI6Ii80NDc0NTk2Ny8zNjUxMDk5NDUtNGQ5ZjBkODAtZmFlNy00NzMyLThlYWEtZTE0NmIxZjRiODk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTM1Y2NjODJkZjVhYzhiMzAzZWE5NjcyMmZkODk5NmQ5NmJmNmVkNDliNzQ4Yzk1YmQxODA4NjI2MTYzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPh0WHR8YwIe1aWKnZAx4wMKLRa1QyFxQciJ1uGOcbY) 分别点击按钮后，控制台如下 ![image](https://private-user-images.githubusercontent.com/44745967/365110992-47fab1a8-00aa-4e9c-be27-2e83bd74333e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njg1OTcsIm5iZiI6MTcyNTY2ODI5NywicGF0aCI6Ii80NDc0NTk2Ny8zNjUxMTA5OTItNDdmYWIxYTgtMDBhYS00ZTljLWJlMjctMmU4M2JkNzQzMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NjIyYWNhZjBkOGYyZmNhMTIzMTlhNGJiM2EyMjZiOWY0YjBlOWM0YTQ1YTllNDA3ZTMxNTIyNzdjYTgzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIvfL1Sb-neWrB6KPb59Es3uBiiu2up_tP1FkrXXQbc)
> 
> 可能现在有了，我等下看看

![image](https://github.com/user-attachments/assets/06f9990f-fa92-44e8-aa56-ff9af54dbbaf)

**Comment by huankong233** [comment]
> > > 好像是有一些区分的， ![image](https://private-user-images.githubusercontent.com/44745967/365109945-4d9f0d80-fae7-4732-8eaa-e146b1f4b894.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njg1OTcsIm5iZiI6MTcyNTY2ODI5NywicGF0aCI6Ii80NDc0NTk2Ny8zNjUxMDk5NDUtNGQ5ZjBkODAtZmFlNy00NzMyLThlYWEtZTE0NmIxZjRiODk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTM1Y2NjODJkZjVhYzhiMzAzZWE5NjcyMmZkODk5NmQ5NmJmNmVkNDliNzQ4Yzk1YmQxODA4NjI2MTYzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPh0WHR8YwIe1aWKnZAx4wMKLRa1QyFxQciJ1uGOcbY) 分别点击按钮后，控制台如下 ![image](https://private-user-images.githubusercontent.com/44745967/365110992-47fab1a8-00aa-4e9c-be27-2e83bd74333e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Njg1OTcsIm5iZiI6MTcyNTY2ODI5NywicGF0aCI6Ii80NDc0NTk2Ny8zNjUxMTA5OTItNDdmYWIxYTgtMDBhYS00ZTljLWJlMjctMmU4M2JkNzQzMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NjIyYWNhZjBkOGYyZmNhMTIzMTlhNGJiM2EyMjZiOWY0YjBlOWM0YTQ1YTllNDA3ZTMxNTIyNzdjYTgzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oIvfL1Sb-neWrB6KPb59Es3uBiiu2up_tP1FkrXXQbc)
> > 
> > 
> > 可能现在有了，我等下看看
> 
> ![image](https://private-user-images.githubusercontent.com/49610758/365336612-06f9990f-fa92-44e8-aa56-ff9af54dbbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODYwOTEsIm5iZiI6MTcyNTY4NTc5MSwicGF0aCI6Ii80OTYxMDc1OC8zNjUzMzY2MTItMDZmOTk5MGYtZmE5Mi00NGU4LWFhNTYtZmY5YWY1NGRiYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA1MDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZWY4MWMwNzFjOTc5NWY5MjI3YWU1YzRmZWVmZTBhMmI4ZjZiY2M4MjkwMjMzNzVkNTBkMzZhZDZjZTJlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTTn8uABON6wHKTGXoO50cOK4D5t_f6xWSGH3sEeN4E)

已发新版，如果 `access_token` 错误会触发 `socket.error` 事件并停止自动重连
