### ISSUE TITLE
socket.error 事件异常

### ISSUE THREAD

**Issue by ry0513** [huankong233/node-napcat-ts#37]
嗨，大佬，我又带着新的问题来了， QAQ
我现在使用的版本为 0.2.11，

**前提条件：我的napcat服务没有启动，此时连接会触发 `socket.error` **

当我配置为
```js
const bot = new NCWebsocket(
  {
    protocol: 'ws',
    host: 'localhost',
    port: 3001,
    accessToken: '' // 请填写你的access_token
  },
  true
)
```
报错信息正常
![image](https://github.com/user-attachments/assets/69d6b3d4-9cd1-477f-be36-be7a996f8002)

但是当我使用IP地址时，例如
```js
const bot = new NCWebsocket(
  {
    protocol: 'ws',
    host: '127.0.0.1',
    port: 3001,
    accessToken: '' // 请填写你的access_token
  },
  true
)
```
则抛出错误为
![image](https://github.com/user-attachments/assets/0c1cc2c8-ec50-400e-8cc1-c8ae5462ea12)

错误原因：
![image](https://github.com/user-attachments/assets/864880fa-db9d-47c4-94e9-fdff1b71da6d)

**Comment by huankong233** [comment]
> 嗨，大佬，我又带着新的问题来了， QAQ 我现在使用的版本为 0.2.11，
> 
> **前提条件：我的napcat服务没有启动，此时连接会触发 `socket.error` **
> 
> 当我配置为
> 
> ```js
> const bot = new NCWebsocket(
>   {
>     protocol: 'ws',
>     host: 'localhost',
>     port: 3001,
>     accessToken: '' // 请填写你的access_token
>   },
>   true
> )
> ```
> 
> 报错信息正常 ![image](https://private-user-images.githubusercontent.com/44745967/365434216-69d6b3d4-9cd1-477f-be36-be7a996f8002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY4NTcsIm5iZiI6MTcyNTc5NjU1NywicGF0aCI6Ii80NDc0NTk2Ny8zNjU0MzQyMTYtNjlkNmIzZDQtOWNkMS00NzdmLWJlMzYtYmU3YTk5NmY4MDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDExNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNGY1OTI5MmMyNmRiYzMwMDBkZGExODM5NDFmMzFmOTI2MDZlMDI5ZmJlMDdlN2U2ZTZlYWQ3ZTE5NTNlOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.copvDkbgdR48-koZqJocuddKmNrCJlI1EFffckb0zlY)
> 
> 但是当我使用IP地址时，例如
> 
> ```js
> const bot = new NCWebsocket(
>   {
>     protocol: 'ws',
>     host: '127.0.0.1',
>     port: 3001,
>     accessToken: '' // 请填写你的access_token
>   },
>   true
> )
> ```
> 
> 则抛出错误为 ![image](https://private-user-images.githubusercontent.com/44745967/365434181-0c1cc2c8-ec50-400e-8cc1-c8ae5462ea12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY4NTcsIm5iZiI6MTcyNTc5NjU1NywicGF0aCI6Ii80NDc0NTk2Ny8zNjU0MzQxODEtMGMxY2MyYzgtZWM1MC00MDBlLThjYzEtYzhhZTU0NjJlYTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDExNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MzM4YjRkODViNjc0YjdmODM3ZGRiYWY1MzAyODczOGEyNGY0ZGY3NDQyMmJmMjg3NzBkY2I3MDRlZTI5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mKx6SLmA2aiGDancgVHz1WG1zNlSq9_C6hjdlIvmkuE)
> 
> 错误原因： ![image](https://private-user-images.githubusercontent.com/44745967/365434445-864880fa-db9d-47c4-94e9-fdff1b71da6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY4NTcsIm5iZiI6MTcyNTc5NjU1NywicGF0aCI6Ii80NDc0NTk2Ny8zNjU0MzQ0NDUtODY0ODgwZmEtZGI5ZC00N2M0LTk0ZTktZmRmZjFiNzFkYTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDExNTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzY2ZmE3YTJkYzZhNDBhZmJhYzUwNGQxOTg5NTgxNmQ3NzRhMjc0YzhhMjRjM2U4MGRkNzJhNzI4ZjM0N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NBja9ECTe2ycpyaoQkM22_wwM0Do0dsUf3hUdefkrvs)

重新写了一下逻辑，再试一下吧，这样应该更合适一些

``` typescript
export type WSErrorRes = {
  reconnection: WSReconnection
} & (
  | {
      error_type: 'response_error'
      info: {
        errno: number
        message: string
        url: string
      }
    }
  | {
      error_type: 'connect_error'
      errors: {
        errno: number
        code: string
        syscall: string
        address: string
        port: number
      }[]
    }
)
```

**Comment by huankong233** [comment]
`v0.2.13`
