### ISSUE TITLE
无法发送消息

### ISSUE THREAD

**Issue by Tackoil** [huankong233/node-napcat-ts#8]
napcat log 显示 JSON 解析错误。复现方式如下

``` TypeScript
bot.on("message.group", async (e) => {
    const textMessage = e.message[0];
    if (textMessage && textMessage.type === "text") {
      const text = textMessage.data.text;
      const code = await bot.send_group_msg({
        group_id: e.group_id,
        message: `我也觉得${text}`,
      });
    }
});
```

看 send 方法的实现，有一点没有理解。这里的 CQEncode 应该不能对整个 message 进行转译。但我对 CQ 协议不太熟悉，不清楚转译应该加在哪里？

https://github.com/huankong233/node-napcat-ts/blob/94e1b36681967af0da31a22b96b36429a0e6e24d/src/NCWebsocketBase.ts#L216

**Comment by huankong233** [comment]
> napcat log 显示 JSON 解析错误。复现方式如下
> 
> ```ts
> bot.on("message.group", async (e) => {
>     const textMessage = e.message[0];
>     if (textMessage && textMessage.type === "text") {
>       const text = textMessage.data.text;
>       const code = await bot.send_group_msg({
>         group_id: e.group_id,
>         message: `我也觉得${text}`,
>       });
>     }
> });
> ```
> 
> 看 send 方法的实现，有一点没有理解。这里的 CQEncode 应该不能对整个 message 进行转译。但我对 CQ 协议不太熟悉，不清楚转译应该加在哪里？
> 
> https://github.com/huankong233/node-napcat-ts/blob/94e1b36681967af0da31a22b96b36429a0e6e24d/src/NCWebsocketBase.ts#L216

是的，这里应该需要修改一下

**Comment by huankong233** [comment]
json 格式的话应该就不需要用到转译了

**Comment by huankong233** [comment]
尝试一下 `0.1.4` 版本

**Comment by Tackoil** [comment]
> 尝试一下 `0.1.4` 版本

解决了，非常感谢。 不过好像还没发布至 npm ？

**Comment by huankong233** [comment]
> > 尝试一下 `0.1.4` 版本
> 
> 解决了，非常感谢。 不过好像还没发布至 npm ？

哈哈，忘记发了，抱歉

**Comment by huankong233** [comment]
已发版
